# default rootski config
host: 0.0.0.0
port: 3333

# used to fetch public JWKs to verify JWT tokens
cognito_aws_region: us-west-2
cognito_user_pool_id: us-west-2_NMATFlcVJ
cognito_web_client_id: 35ufe1nk2tasug2gmbl5l9mra3

extra_allowed_cors_origins:
  - http://localhost:3333
  - http://localhost:3000

log_level: INFO
